from __future__ import annotations

from typing import Protocol

from threaddesk.core.models import Snapshot, Thread


class Store(Protocol):
    def list_threads(self, include_archived: bool = False) -> list[Thread]: ...
    def get_thread(self, thread_id: str) -> Thread: ...
    def save_thread(self, thread: Thread) -> None: ...
    def delete_thread(self, thread_id: str) -> None: ...
    def get_current_id(self) -> str | None: ...
    def set_current_id(self, thread_id: str | None) -> None: ...
    def save_snapshot(self, snap: Snapshot) -> None: ...
    def get_snapshot(self, snap_id: str) -> Snapshot: ...
    def list_snapshots(self, thread_id: str) -> list[Snapshot]: ...
