"""Storage contracts shared by JSON today and SQLite later."""

from __future__ import annotations

from contextlib import AbstractContextManager
from pathlib import Path
from typing import Any, Mapping, Protocol

from threaddesk.core.models import GraphEvent, KnowledgeNode, Relation, Snapshot, Thread


class ThreadStore(Protocol):
    def list_threads(self, include_archived: bool = False) -> list[Thread]: ...
    def get_thread(self, thread_id: str) -> Thread: ...
    def save_thread(self, thread: Thread) -> None: ...
    def delete_thread(self, thread_id: str) -> None: ...
    def get_current_id(self) -> str | None: ...
    def set_current_id(self, thread_id: str | None) -> None: ...


class SnapshotStore(Protocol):
    def save_snapshot(self, snap: Snapshot) -> None: ...
    def get_snapshot(self, snap_id: str) -> Snapshot: ...
    def list_snapshots(self, thread_id: str) -> list[Snapshot]: ...


class GraphStore(Protocol):
    def save_node(self, node: KnowledgeNode) -> None: ...
    def get_node(self, node_id: str) -> KnowledgeNode: ...
    def list_nodes(self) -> list[KnowledgeNode]: ...
    def save_relation(self, relation: Relation) -> None: ...
    def list_relations(self) -> list[Relation]: ...
    def append_graph_event(self, event: GraphEvent) -> None: ...
    def list_graph_events(self) -> list[GraphEvent]: ...


class ArtifactStore(Protocol):
    def artifact_path(self, name: str) -> Path: ...
    def write_json_artifact(self, name: str, data: Mapping[str, Any]) -> Path: ...
    def write_text_artifact(self, name: str, text: str) -> Path: ...


class ImportBatchStore(Protocol):
    def save_import_batch(self, batch_id: str, data: Mapping[str, Any]) -> None: ...
    def get_import_batch(self, batch_id: str) -> dict[str, Any]: ...
    def list_import_batches(self) -> list[dict[str, Any]]: ...


class UnitOfWork(Protocol):
    def transaction(self) -> AbstractContextManager[None]: ...


class Store(ThreadStore, SnapshotStore, GraphStore, ArtifactStore, Protocol):
    """Minimum application store contract before import is enabled."""
